name: Release

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    name: Build and Attach Artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify PowerShell version (>= 7.2)
        shell: pwsh
        run: |
          $v = $PSVersionTable.PSVersion
          Write-Host "Using PowerShell $($PSVersionTable.PSEdition) $v"
          if ($PSVersionTable.PSEdition -ne 'Core' -or $v -lt [version]'7.2') {
            throw "PowerShell 7.2+ (Core) is required. Current: $($PSVersionTable.PSEdition) $v"
          }

      - name: Install Pester & PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module Pester -Scope CurrentUser -Force -MinimumVersion 5.5.0
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Run PSScriptAnalyzer (errors only)
        shell: pwsh
        run: |
          Import-Module PSScriptAnalyzer
          $results = Invoke-ScriptAnalyzer -Path src -Recurse -Severity Error
          if ($results) {
            $results | Format-Table -AutoSize | Out-String | Write-Host
            throw 'PSScriptAnalyzer found errors.'
          }

      - name: Run Tests (Pester 5)
        shell: pwsh
        run: |
          ./scripts/Invoke-Tests.ps1

      - name: Package module artifact
        shell: pwsh
        run: |
          $dest = "port-api-${{ matrix.os }}.zip"
          if (Test-Path $dest) { Remove-Item $dest -Force }
          Compress-Archive -Path src/Port.Api/* -DestinationPath $dest -Force
          Write-Host "Created artifact: $dest"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            port-api-${{ matrix.os }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

